spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
logging:
  level:
    #org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
jwt:
  issuer: content-commerce.com
  secret-key: content-commerce