spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
jwt:
  issuer: content-commerce.com
  secret-key: content-commerce